### ISSUE TITLE
Improve management of the screenshots

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-docs#112]
Implement a script to:
1. get the latest skills-service 
1. populate with sample data 
1. run cypress tests that generate screenshots 
1. store them in a well-known directory 

This script can then be executed every release and the screenshots will automatically update as long the file names are persistent

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-docs/pull/116

**Comment by rmmayo** [comment]
:+1:
