### ISSUE TITLE
passAuthInstallOnly=true builds docs still mentioning PKI auth

### ISSUE THREAD

**Issue by ventralnet** [NationalSecurityAgency/skills-docs#141]
If you build skilltree docs with the build flag passAuthInstallOnly=true  PKI authentication is still mentioned in second bullet in the authentication documentation information
<documentation url>/skills-client/auth.html

The text is
"In PKI Mode: User's id is derived implicitly from the certificate, an authentication endpoint is not required"

**Comment by sudo-may** [comment]
PR: https://github.com/NationalSecurityAgency/skills-docs/pull/142
