### ISSUE TITLE
Projects to contribute to wanted

### ISSUE THREAD

**Issue by evenstensberg** [NationalSecurityAgency/skills-docs#297]
Hi. I have some time to spend and would like to contribute to the NSA. Atm I'm contributing to mi6/mi5/gchq, but would like to add value to your organization too. Is there any repo you need a hand on?

**Comment by sudo-may** [comment]
We cannot speak for NSA but if you are interested in contributing to SkillTree please take a look at 

- [https://github.com/NationalSecurityAgency/skills-service/issues](https://github.com/NationalSecurityAgency/skills-service/issues)
- [https://skilltreeplatform.dev/contribution](https://skilltreeplatform.dev/contribution)

Have a wonderful day!
