### ISSUE TITLE
Document Native JS SkillsLevelJS component

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-docs#3]
Document Native JS ``SkillsLevelJS`` component

**Comment by rmmayo** [comment]
@sudo-may a section was added on [rmmayo/#34_pure_js_level_section](https://github.com/NationalSecurityAgency/skills-docs/compare/rmmayo/%2334_pure_js_level_section).  There was already a ticket in gitlab that I assign to you for review.

**Comment by rmmayo** [comment]
created a pull request in [GitGub](https://github.com/NationalSecurityAgency/skills-docs/pull/4)
