### ISSUE TITLE
Latest tag for skills-service image

### ISSUE THREAD

**Issue by tpugh** [NationalSecurityAgency/skills-docs#34]
Currently under the quick start documentation the _Option 1 - Docker-based install_ instructs the user to perform the following command.
`docker run --name skills-service -d -p 8080:8080 skilltree/skills-service:latest` 

After reviewing it seems as though the skills-service does not currently have a tag _latest_. It seems as though we have two options to help users not receive docker: Error response from daemon:manifest for skilltree/skills-service:latest not found: manifest unknown: manifest unknown. One option is to add latest as a tag or update the quick start docker run command in the quick start directions.

**Comment by sudo-may** [comment]
@tpugh thanks for reporting. Made the fix. This fix was already made in https://github.com/NationalSecurityAgency/skills-docs/issues/21; however that ticket may not get finished and reviewed until later today or tomorrow. This will get the fix in quicker. 

PR: https://github.com/NationalSecurityAgency/skills-docs/pull/35

**Comment by rmmayo** [comment]
verified the change has been published.
