### ISSUE TITLE
Document new Progress and Ranking views

### ISSUE THREAD

**Issue by sudo-may** [NationalSecurityAgency/skills-docs#67]
Document new Progress and Ranking views
- Since 1.4.0
- new default landing page
- visualize user's progress and ranking across all of the integrated projects
- provides capability to drill down to each project and view its Skills Display
- added the ability to customize landing page between Progress and Ranking and the original Project Admin view
- project admin can place the project into the production mode via the Settings page which will then display that project on the Progress and Ranking page

**Comment by rmmayo** [comment]
:+1:
